### ISSUE TITLE
Getting same output value for taxa across sample groups?

### ISSUE THREAD

**Issue by scubalaina** [mooreryan/divnet-rs#11]
Hi there,

I ran divnet-rs on a dataset with 1666 taxa and 31 samples; the samples belong to two groups (15 to group WAR or 16 to group EPR). My goal is to test differences in alpha diversity between these two groups. I successfully ran divnet-rs, but when I used the code from the walk-through on `3_import_divnet_rs_data.R` , with my own output file, I noticed the Shannon's diversity estimate was the same for each sample within the same group for some reason. I then noticed in the output table from divnet-rs that each taxa's estimated value was the same across samples belonging to the same group (per replicate). I suspect this is causing the downstream issues, but I'm not sure how this happened in the first place. I attached my input files and the output - I renamed with the ".txt" at the end so github would accept them as an attachment. Thank you so much for your time and help!
[pan2_cog85_relabund_reefs.csv.txt](https://github.com/mooreryan/divnet-rs/files/11790021/pan2_cog85_relabund_reefs.csv.txt)
[pan2_cog85_divnet.toml.txt](https://github.com/mooreryan/divnet-rs/files/11790017/pan2_cog85_divnet.toml.txt)
[pan2_cog85_reef_divnet_output.csv.txt](https://github.com/mooreryan/divnet-rs/files/11790019/pan2_cog85_reef_divnet_output.csv.txt)

**Comment by mooreryan** [comment]
Hey, thanks for your question.

> I noticed the Shannon's diversity estimate was the same for each sample within the same group for some reason. I then noticed in the output table from divnet-rs that each taxa's estimated value was the same across samples belonging to the same group (per replicate).

^ This is how DivNet is supposed to work:  rather than giving you estimates of diversity based on each sample, it uses the info from the biological replicates and covariate info to try and estimate the diversity of whatever ecosystem/treatment/grouping/whatever that you are interested in.  So, given the way the method works, you will get the same alpha estimates and taxa's estimated relative abundance being the same within each group specified by your model/covariates.

The [getting started](https://github.com/adw96/DivNet/blob/main/vignettes/getting-started.Rmd) vignette has a nice overview, if you haven't seen that yet.

**Comment by scubalaina** [comment]
Hi there,

Okay great! I see in the example output now, as well. Sorry for my
confusion!

Thanks,
Alaina :)

**Comment by mooreryan** [comment]
No worries, it was a good question.  I have updated the [docs](https://mooreryan.github.io/divnet-rs-book/lee_data_walkthrough.html#plots) to hopefully better address this issue for future users.

Let me know if you have any more issues!
